name: HA plugin build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - shell: bash
    - name: Log in to Docker Hub
      env:
        USERNAME: ${{ secrets.DOCKERUSERNAME }}
        PASSWORD: ${{ secrets.DOCKERPASSWORD }}
      run: docker login -u %USERNAME% -p %PASSWORD%
    - name: Build the Docker image
      run: docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock:ro homeassistant/amd64-builder --all -t aquarea2mqtt -r https://github.com/rondoval/ha-addons -b master
